processes:
  - type: "srsue"
    config_file: "configs/zmq/multi/ue1_zmq.conf"
  - type: "srsue"
    config_file: "configs/zmq/multi/ue2_zmq.conf"
  - type: "srsue"
    config_file: "configs/zmq/multi/ue3_zmq.conf"

data_export:
  output_directory: "/tmp/"
  iq_capture: true
  iperf_capture: true
