processes:
  - type: "srsue"
    config_file: "configs/uhd/multi_ue/ue1_uhd.conf"
  - type: "srsue"
    config_file: "configs/uhd/multi_ue/ue2_uhd.conf"

influxdb:
  influxdb_host: ${DOCKER_INFLUXDB_INIT_HOST}
  influxdb_port: ${DOCKER_INFLUXDB_INIT_PORT}
  influxdb_org: ${DOCKER_INFLUXDB_INIT_ORG}
  influxdb_token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

data_backup:
  backup_every: 1000
  backup_dir: test
  backup_dir: -1d
