services:
  srsue:
    container_name: srsran/ue
    image: srsran/ue
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    privileged: true
    env_file:
      - .env
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Access UHD images
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Store logs in /tmp
      - /tmp:/tmp

    environment:
      - CONFIG=${DOCKER_SRSUE_INIT_CONFIG:-configs/zmq/ue_zmq_docker.conf}
      - ARGS=${DOCKER_SRSUE_INIT_ARGS}

    # Allow network connection for ZMQ
    ports:
       -  2000:2000/tcp
       -  2001:2001/tcp
    networks:
      -  srsue_network

  controller:
    container_name: controller
    image: controller
    volumes:
      # Pass in the docker soket for starting srsue
      - /var/run/docker.sock:/var/run/docker.sock
      # Allow results writing to host machine
      - /tmp:/tmp
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONFIG=${DOCKER_CONTROLLER_INIT_CONFIG:-configs/basic_ue_zmq.yaml}
    privileged: true
    build:
      context: controller
    env_file:
      - .env
    networks:
      metrics:
        ipv4_address: 172.19.1.7

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      # Enable writing data backups to the host machine
      - /tmp/:/tmp/host/
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    # Uncomment port section to access InfluxDB from outside the docker network
    ports:
      - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.5

  grafana:
    container_name: grafana
    image: srsran/grafana
    build:
      context: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.6


volumes:
  ue-storage:
  influxdb-storage:
  grafana-storage:

networks:
  srsue_network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.18.0.0/24

  metrics:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
