services:
  srsue:
    container_name: srsran_ue
    image: srsran/ue
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    privileged: true
    env_file:
      - .env
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Access UHD images
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Store logs in /tmp
      - ue-storage:/tmp
    environment:
      - CONFIG=${UE_CONFIG_PATH:-configs/zmq/ue_zmq.conf}
      - ARGS=${UE_ARGS}
    # Allow network connection for ZMQ
    ports:
      -  2000:2000/tcp
      -  2001:2001/tcp
    network_mode: host

  controller:
    container_name: controller
    image: controller
    build:
      context: controller
    env_file:
      - .env
    environment:
      - CONFIG=${UE_CONTROLLER_CONFIG}
    ports:
      - 5050:${UE_CONTROLLER_PORT}/tcp
    networks:
      controller:
        ipv4_address: 172.19.1.4

  webui:
    container_name: webui
    image: webui
    build:
      context: webui
    env_file:
      - .env
    environment:
      - PORT=${WEBUI_PORT}
    networks:
    - internal_network
    ports:
      - 3000:${WEBUI_PORT}/tcp
      - "127.0.0.1:8765-8865:8765-8865"

volumes:
  ue-storage:

networks:
  internal_network:
    driver: bridge
  controller:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
