services:
  srsue:
    container_name: srsran_ue
    image: srsran/ue
    build:
      context: ..
      dockerfile: docker/dockerfile
      args:
        os_version: "24.04"
    privileged: true
    env_file:
      - .env
    cap_add:
      - sys_nice
      - cap_sys_ptrace
    volumes:
      # access usb to use some sdrs
      - /dev/bus/usb/:/dev/bus/usb/
      # access uhd images
      - /usr/share/uhd/images:/usr/share/uhd/images
      # store logs in /tmp
      - ue-storage:/tmp
    environment:
      - config=${ue_config_path:-configs/zmq/ue_zmq.conf}
      - args=${ue_args}
    # allow network connection for zmq
    ports:
      -  2000:2000/tcp
      -  2001:2001/tcp
    network_mode: host

  controller:
    container_name: controller
    image: controller
    build:
      context: controller
    env_file:
      - .env
    environment:
      - config=${ue_controller_config}
    ports:
      - 5050:${ue_controller_port}/tcp
    networks:
      controller:
        ipv4_address: 172.19.1.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ue-storage:

networks:
  controller:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
