gnb:
  config: "../../configs/zmq/gnb_zmq.yaml"
  ip: "127.0.0.1"
  port: 5000

namespaces:
  - name: "ue1"

processes:
  - type: "tester" # This means attack
    config_file: "../../configs/zmq/ue_zmq.conf"
    args: "--rrc.sdu_fuzzed_bits 1 --rrc.fuzz_target_message 'rrcSetupRequest'" # this means fuzz bits in the rrc setup
