processes:
  - type: "rtue"
    config_file: "configs/zmq/ue_zmq_docker.conf"

influxdb:
  influxdb_host: ${DOCKER_INFLUXDB_INIT_HOST}
  influxdb_port: ${DOCKER_INFLUXDB_INIT_PORT}
  influxdb_org: ${DOCKER_INFLUXDB_INIT_ORG}
  influxdb_token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
